// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjP_THJCK3pTW7NQZ67MGr1MoAjAIxxx0',
    appId: '1:355565023430:web:898563d3864dac9bf027c7',
    messagingSenderId: '355565023430',
    projectId: 'flutterfire-cli-fffba',
    authDomain: 'flutterfire-cli-fffba.firebaseapp.com',
    storageBucket: 'flutterfire-cli-fffba.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwgwFd2N5QRstcQNx7vJWaDI6x4PHgMyY',
    appId: '1:355565023430:android:f3da185e47767693f027c7',
    messagingSenderId: '355565023430',
    projectId: 'flutterfire-cli-fffba',
    storageBucket: 'flutterfire-cli-fffba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdk202tCG2CvgwFfnPQwm7eapOn7oRbl0',
    appId: '1:355565023430:ios:ef7986ff4a9bdc60f027c7',
    messagingSenderId: '355565023430',
    projectId: 'flutterfire-cli-fffba',
    storageBucket: 'flutterfire-cli-fffba.appspot.com',
    iosBundleId: 'com.example.flutterRemoteConfigServerDrivenUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdk202tCG2CvgwFfnPQwm7eapOn7oRbl0',
    appId: '1:355565023430:ios:3c60cb6681ec558af027c7',
    messagingSenderId: '355565023430',
    projectId: 'flutterfire-cli-fffba',
    storageBucket: 'flutterfire-cli-fffba.appspot.com',
    iosBundleId: 'com.example.flutterRemoteConfigServerDrivenUi.RunnerTests',
  );
}
